BASE_URL = "https://resultados.gob.ar/backend-difu-arg/scope/data/getScopeData"
ERRORES_SEGUIDOS_PERMITIDOS = 5
RESULTS_COLUMNS = ["provincia", "municipio", "circuito", "escuela", "mesa", "codigo_lista", "votos"]
RESULTS_COLUMNS_FITU = ["mesa", "votos_fitu", "votos_pts", "votos_mst", "total_votos", "total_votos_afirmativos", "total_votos_validos"]
DATOS_INTERESANTES = ["electores", "sobres", "nulos", "recurridos", "blancos", "impugnados", "totalVotos", "afirmativos", "abstencion", "valid"]

codigos_fitu_partido = {
    1: "13",
    2: "41",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
}

codigos_lista_pts = {
    1: "2",
    2: "2",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
}

codigos_lista_mst = {
    1: "1",
    2: "1",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
}
